config/routes.rb
Rails.application.routes.draw do


  get 'hobbies/new'

  resources :people, shallow: true do
    resources :hobbies
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
# == Schema Information
#
# Table name: hobbies
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  kind        :integer
#  person_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_hobbies_on_person_id  (person_id)
#

class Hobby < ApplicationRecord
  belongs_to :person
  enum kind: {indoors: 0, outdoors: 1}
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  birthdate  :date
#  gender     :integer
#  dni        :string
#  customer   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Person < ApplicationRecord
    has_many :hobbies 
    enum gender: {male: 0, female: 1, unkown: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  def new
    @person = Person.find_by(id: params[:person_id])
    @hobby = @person.hobbies.build
    @kind = Hobby.kinds.keys
  end

  def create
    @person = Person.find_by(id: params[:person_id])
    @hobby = @person.hobbies.build(hobby_params)
    if @hobby.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  private

  def hobby_params
    params.require(:hobby).permit(:name, :description,:kind, :person_id)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all

  end

  def show; end

  def new
    @person = Person.new 
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit; end

  def update; end

  def destroy; end

  private
  
    def person_params
      params.require(:person).permit(:name, :email, :birthdate,
                                   :gender, :dni, :customer)
    end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/hobbies/new.html.haml
%h1 Hobbies#new

= form_with(model: [@person, @hobby], local: true) do |form|
    .field
        = form.label :name
        = form.text_field :name
    .field
        = form.label :description
        = form.email_field :description
    .field
        = form.label :kind
        = form.select :kind, options_for_select(@kind)
    .field
        = form.hidden_field :person_id
    = form.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helpers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.haml
%h1 People
- if @people.empty?
    %h4 No people!
- else
%table{:border => 5}
    %theader
        %th Name
        %th Email
        %th Birthdate
        %th Gender
        %th DNI
        %th Customer
    %tbody
    - @people.each do |value|
        %tr
            %td= value.name
            %td= value.email
            %td= value.birthdate
            %td= value.gender
            %td= value.dni
            %td= value.customer

%br/ 

= link_to 'New people',new_person_path 

        

app/views/people/new.html.haml
= link_to 'Back', people_path

%h4 Create new person

-# %form{:action => people_path,:method => "post"}
-#    %label Name
-#    %input{:name => "person[name]", :type => "text"}/
-#    %br/
-#    %label Email
-#    %input{:name => "person[email]", :type => "email"}/
-#    %br/
-#    %label Birthdate
-#    %input{:name => "person[birthdate]", :type => "date"}/
-#    %br/
-#  %label Gender
-#   %br/
-#    %label Female
-#    %input{:name => "person[gender]", :type => "radio",:value => "female"}/
-#    %label Male
-#    %input{:name => "person[gender]", :type => "radio",:value => "male"}/
-#    %br/
-#    %label DNI
-#    %input{:name => "person[dni]", :type => "text"}/
-#    %br/
-#    %label Customer
-#    %br/
-#    %label True
-#    %input{:name => "person[customer]", :type => "radio",:value => "true"}/
-#    %label False
-#    %input{:name => "person[customer]", :type => "radio",:value => "false"}/
-#    %br/
-#    %button{:type => "submit"} Send
-#    %input{type: 'hidden', value: form_authenticity_token, name: 'authenticity_token'}

= form_with(model: @person, local: true) do |form|
    .field
        = form.label :name
        = form.text_field :name
    .field
        = form.label :email
        = form.email_field :email
    .field
        = form.label :birthdate
        = form.date_field :birthdate
    .field
        = form.label :gender
        = form.select :gender, [['Male','male'],['Female','female'],['Unknown','unknown']]
    .field
        = form.label :dni
        = form.number_field :dni
    .field
        = form.label :customer?
        .field
            = form.label :yes
            = form.radio_button :customer, true, checked: true
        .field
            = form.label :no
            = form.radio_button :customer, false
    = form.submit

   
    